// Data + i18n for the SPU printing service prototype.
export const TH = {
  appName:"ระบบใช้บริการโรงพิมพ์", org:"โรงพิมพ์ กลุ่มงานโครงสร้างพื้นฐาน", tel:"โทร. 02 579 1111 ต่อ 1114, 1552",
  roleReq:"ผู้รับบริการ", roleAdmin:"แอดมินโรงพิมพ์", roleExec:"ผู้บริหาร",
  tabLanding:"รับบริการ", tabWizard:"แบบฟอร์มบริการ", tabMine:"งานของฉัน", tabTrack:"ติดตามสถานะ",
  tabQueue:"คิวงาน", tabMobile:"อัปเดตจากมือถือ", tabPrice:"ตารางราคา", tabRaw:"รายการคำขอรับบริการ",
  tabSheet:"โครงสร้างชีต", tabSettings:"ตั้งค่าเชื่อมต่อ", tabDash:"แดชบอร์ด", tabReport:"เอกสารสรุปรายงาน",
  kicker:"โรงพิมพ์ให้บริการ งานผลิต งานพิมพ์และออกแบบ",
  landH1:"โรงพิมพ์ มหาวิทยาลัยศรีปทุม ยินดีให้บริการ",
  landSub:"ฟอร์มเดียวสำหรับทุกงานพิมพ์ เลือกบริการที่ต้องการ ระบบถามเฉพาะคำถามที่เกี่ยวข้อง คำนวณราคาประมาณการ และให้ติดตามสถานะได้จนรับงาน",
  ctaNew:"เริ่มใช้บริการ", ctaTrack:"ติดตามงานของฉัน",
  pickService:"บริการทั้งหมด", pickServiceSub:"ราคาที่แสดงมาจากตารางราคาปัจจุบัน รายการที่ยังไม่มีราคาจะขึ้นสถานะรอประเมินราคา ไม่แสดงเป็น 0 บาท",
  chooseThis:"เลือกกลุ่มนี้",
  statReq:"คำขอเดือนนี้", statUser:"ผู้ใช้บริการไม่ซ้ำ", statUnit:"หน่วยงานที่ใช้บริการ", statValue:"มูลค่างานเดือนนี้",
  oneForm:"บันทึกข้อมูล สะดวก รวดเร็ว ในทุกบริการ", newRequest:"แบบฟอร์มรับบริการ", stepWord:"ขั้นที่",
  ws1:"เลือกบริการ", ws2:"ข้อมูลและรายละเอียด", ws3:"แนบไฟล์", ws4:"ตรวจสอบและส่ง",
  s1title:"เลือกบริการที่ต้องการ", s1sub:"เลือกได้หลายรายการในคำขอเดียว เช่น พริ้นสี + เข้าเล่ม",
  s2title:"ข้อมูลผู้ขอใช้บริการ", dynFields:"คำถามเพิ่มเติมตามบริการที่เลือก", qty:"จำนวน",
  emptySel:"ยังไม่ได้เลือกบริการ กลับไปขั้นที่ 1 เพื่อเลือกก่อน",
  s3title:"แนบไฟล์งาน", dropTitle:"ลากไฟล์มาวาง หรือเลือกจากเครื่อง",
  dropHint:"สูงสุด 10 ไฟล์ ไฟล์ละไม่เกิน 10 MB · PDF, DOCX, XLSX, PPTX, JPG, PNG", chooseFile:"เลือกไฟล์",
  driveTitle:"ไฟล์เก็บที่ Google Drive", driveNote:"ระบบสร้างโฟลเดอร์ตามเลขที่งานอัตโนมัติ ชีตเก็บเพียงรหัสไฟล์และลิงก์ ไม่เก็บตัวไฟล์",
  s4title:"สรุปราคาประมาณการ", s4sub:"ราคานี้เป็นราคาประมาณการ จะกลายเป็นราคายืนยันเมื่อเจ้าหน้าที่โรงพิมพ์ตรวจสอบแล้ว",
  colService:"บริการ", colQty:"จำนวน", colUnitPrice:"ราคา/หน่วย", colAmount:"เป็นเงิน",
  estTotal:"ราคาประมาณการรวม", submit:"ส่งคำขอ", cancel:"ยกเลิก", back:"ย้อนกลับ", next:"ถัดไป",
  submitOk:"ส่งคำขอสำเร็จ เลขที่งาน", submitOkSub:"ระบบส่งอีเมลยืนยันไปที่บัญชี @spu.ac.th ของคุณแล้ว และบันทึกลงแท็บ JOBS ในสเปรดชีต", viewTrack:"ดูสถานะงาน",
  myJobs:"งานของฉัน", jobNo:"เลขที่งาน", sent:"วันที่ส่ง", needBy:"ต้องการรับงาน", est:"ประมาณการ", confirmed:"ราคายืนยัน", status:"สถานะ",
  mineNote:"กดที่แถวเพื่อดูไทม์ไลน์และไฟล์ของงานนั้น ผู้ขอเห็นได้เฉพาะงานของตนเอง",
  trackKicker:"ติดตามสถานะงาน", timeline:"ไทม์ไลน์สถานะ", jobDetail:"รายละเอียดงาน", filesTitle:"ไฟล์งาน",
  filesNote:"ไฟล์เปิดได้เฉพาะผู้ขอใช้บริการและเจ้าหน้าที่โรงพิมพ์ ไม่ตั้งเป็นลิงก์สาธารณะ",
  queue:"คิวงานโรงพิมพ์", searchPh:"ค้นหาเลขที่งาน ชื่อ หรือหน่วยงาน", requester:"ผู้ขอ", unit:"หน่วยงาน", action:"เปลี่ยนสถานะ",
  kpiReceived:"ได้รับไฟล์แล้ว", kpiNew:"กำลังผลิต", kpiProd:"เสร็จสิ้นการผลิต", kpiReady:"เสร็จสิ้นการบริการ", kpiOver:"เกินกำหนด",
  mobileTitle:"อัปเดตสถานะจากมือถือ", mobileSub:"หน้าจอสำหรับเจ้าหน้าที่หน้าเครื่อง กดปุ่มเดียวเปลี่ยนสถานะ บันทึกลงชีต และส่งอีเมลแจ้งผู้ขอทันที",
  mobileApp:"งานวันนี้", today:"วันนี้", fToday:"งานวันนี้", fPending:"งานค้าง", fReady:"พร้อมรับ",
  logTitle:"บันทึกการเปลี่ยนสถานะ", logNote:"ทุกการเปลี่ยนสถานะบันทึกลงแท็บ STATUS_LOG พร้อมผู้กด เวลา และหมายเหตุ",
  priceMaster:"ตารางราคา", priceMasterSub:"แอดมินแก้ราคาได้จากหน้านี้ ไม่ต้องแก้โค้ด ราคาที่ใช้คำนวณถูกบันทึกติดไปกับงาน รายงานย้อนหลังจึงไม่เปลี่ยน",
  addRule:"เพิ่มรายการราคา", spec:"เงื่อนไข", priceType:"รูปแบบราคา", price:"ราคา (บาท)", effective:"เริ่มใช้",
  priceRuleTitle:"กติกาที่ระบบบังคับใช้",
  rawData:"ข้อมูลการคำขอรับบริการ", exportCsv:"Export CSV", exportXlsx:"Export XLSX",
  rawNote:"หนึ่งแถวคือหนึ่งรายการบริการ (line item) การรวมยอดทำที่ระดับงานเพื่อไม่ให้นับซ้ำ",
  dashKicker:"สำหรับผู้บริหาร อ่านได้เท่านั้น", dashboard:"รายงานการให้บริการ",
  chartMonthly:"จำนวนใช้บริการรายเดือน", chartTopService:"บริการที่ใช้มากที่สุด", chartStatus:"งานตามสถานะ",
  fYear:"ปี", fMonth:"เดือน", fUnitF:"หน่วยงาน", allUnits:"ทุกหน่วยงาน",
  fYearBE:"ปี พ.ศ.", fYearAcademic:"ปีการศึกษา", fAllMonths:"ทั้งปี", periodLabel:"ช่วงข้อมูล",
  topRequesters:"Top 10 ผู้เข้ารับบริการ", topUnitsValue:"หน่วยงานใช้บริการมากที่สุด (ตามค่าบริการ)", timesSuffix:"ครั้ง",
  kpiAll:"คำขอทั้งหมด", kpiUniqUser:"ผู้ใช้ไม่ซ้ำ", kpiUniqUnit:"หน่วยงาน", kpiDone:"งานเสร็จ", kpiValue:"มูลค่างานรวม", kpiTat:"เวลาทำงานเฉลี่ย",
  kpiAllSub:"สถานะคำขอรับบริการทั้งหมด", kpiUserSub:"@spu.ac.th (ไม่นับซ้ำ)", kpiUnitSub:"หน่วยงานที่มีคำขอ",
  kpiDoneSub:"งานส่งมอบเสร็จสิ้น", kpiValueSub:"ตามมูลค่า ค่าบริการโรงพิมพ์", kpiTatSub:"ส่งคำขอ ถึง ส่งมอบงาน",
  a4Title:"รายงานสรุปรายเดือน A4", a4Sub:"ยอดรวมมาจากข้อมูลชุดเดียวกับข้อมูลดิบและแดชบอร์ด",
  printPdf:"พิมพ์ / บันทึก PDF", a4Head:"สรุปการขอใช้บริการ โรงพิมพ์", a4Period:"ประจำเดือนสิงหาคม 2568",
  a4Intro:"เรียน ผู้อำนวยการกลุ่มงานโครงสร้างพื้นฐาน — โรงพิมพ์ขอส่งสรุปการขอใช้บริการประจำเดือน แยกตามหน่วยงานและประเภทงาน ดังตารางต่อไปนี้",
  a4Foot:"หมายเหตุ: มูลค่างานใช้ราคายืนยันเป็นหลัก รายการที่ยังไม่ยืนยันราคาแสดงเป็นราคาประมาณการและกำกับ * งานที่ยกเลิกไม่นับรวมในมูลค่า",
  docNo:"เลขที่", docDate:"วันที่", monthAug:"สิงหาคม", grandTotal:"รวมเป็นเงิน",
  catProd:"งานผลิต", catDesign:"งานพิมพ์และออกแบบ", catColor:"พริ้นสี", cnt:"จำนวน", amt:"มูลค่า",
  signName:"(หัวหน้าโรงพิมพ์)", signRole:"โรงพิมพ์ กลุ่มงานโครงสร้างพื้นฐาน",
  sheetKicker:"สถาปัตยกรรมข้อมูล", sheetTitle:"ข้อมูลทั้งหมดอยู่ใน Google Sheet ไฟล์เดียว",
  sheetSub:"ไม่มีฐานข้อมูลแยก ไม่ใช้ Supabase หนึ่งสเปรดชีตเก็บทุกแท็บ ไฟล์งานอยู่บน Google Drive และชีตเก็บเพียงรหัสไฟล์กับลิงก์",
  tabsTitle:"แท็บในสเปรดชีต", tabsSub:"กดแท็บเพื่อดูโครงคอลัมน์ ชื่อคอลัมน์ในแถวที่ 1 คือสัญญาข้อมูล ห้ามสลับลำดับ ให้เพิ่มคอลัมน์ใหม่ต่อท้ายเท่านั้น",
  emailGateTitle:"รับบริการงานผลิตและงานพิมพ์", emailGateLabel:"อีเมล @spu.ac.th", emailGatePh:"เช่น somchai.j@spu.ac.th",
  emailGateBtn:"ขอรับบริการ", emailGateErr:"กรุณากรอกอีเมลที่ลงท้าย @spu.ac.th", emailGateFound:"พบข้อมูลของท่านแล้ว ตรวจสอบและแก้ไขได้ก่อนส่ง", emailGateNotFound:"ไม่พบข้อมูลในระบบ กรุณากรอกข้อมูลให้ครบทุกช่อง",
  wzService:"เลือกบริการ", wzDetails:"ข้อมูลและรายละเอียด", wzFiles:"แนบไฟล์", wzReview:"ตรวจสอบและส่ง",
  svcGroupProd:"งานผลิต", svcGroupDesign:"งานพิมพ์และออกแบบ",
  prodColor:"สี หรือ ขาวดำ", prodColorColor:"สี", prodColorBw:"ขาวดำ",
  prodSize:"ขนาดกระดาษ", prodSizeA3:"A3 (ใหญ่)", prodSizeA4:"A4 (ปกติ)", prodSizeA5:"A5 (เล็ก)",
  prodPaperType:"ประเภทกระดาษ", prodSides:"หน้าเดียว / สองหน้า", prodSidesOne:"หน้าเดียว", prodSidesTwo:"สองหน้า",
  prodOwnPaper:"นำกระดาษมาเอง", prodOwnPaperWarn:"กระบวนการจะเริ่มหลังจากโรงพิมพ์ได้รับกระดาษ",
  prodQty:"จำนวน (แผ่น)",
  prodQtyOriginal:"จำนวนต้นฉบับ (แผ่น)", prodQtySets:"จำนวนชุดที่ต้องการ",
  stapleLabel:"การเย็บชุด", stapleCorner:"เย็บมุม", stapleSide2:"เย็บข้าง 2 จุด", stapleNone:"ไม่เย็บชุด",
  examTitle:"รายละเอียดข้อสอบ", examType:"ประเภทการสอบ", examMid:"สอบกลางภาค", examOut:"สอบนอกตาราง",
  examSubject:"รายวิชา (รหัสวิชา + ชื่อวิชา)", examSubjectPh:"เช่น BUS201 หลักการตลาด",
  examNote:"ทางคณะส่งไฟล์ข้อสอบมาให้โรงพิมพ์ กรอกรายละเอียดตามงานพิมพ์สำเนา และระบุรายวิชา",
  budgetTitle:"งบประมาณ", budgetSub:"ระบุแหล่งงบประมาณของงานนี้",
  budgetHas:"มีงบ (มูลค่างาน)", budgetProject:"โอนจ่าย (งบโครงการ)", budgetPersonal:"โอนจ่าย (งบส่วนตัว)",
  budgetAttach:"แนบไฟล์งบที่อนุมัติ", budgetAttachHint:"PDF หรือรูปถ่ายเอกสารอนุมัติงบ",
  budgetAcct:"แจ้งเลขบัญชี มศป.", budgetAcctPh:"มศป. …",
  budgetSkip:"งานพิมพ์สำเนาข้อสอบและแบบฝึกหัดเป็นบริการที่โรงพิมพ์ให้อยู่แล้ว ไม่ต้องระบุงบประมาณ",
  priceActive:"เปิดใช้งาน", priceOffLabel:"ปิดใช้งาน", priceToggleCol:"เปิด/ปิด",
  formulaTitle:"สูตรคำนวณ", formulaSub:"ใช้ตรวจสอบยอดก่อนยืนยันราคา", calcTitle:"เครื่องคิดเลข", calcOpenHint:"เปิดหน้าต่างลอย", calcKbHint:"พิมพ์จากคีย์บอร์ดได้ · Enter = เท่ากับ · Esc ปิด", calcClear:"ล้าง",
  fCol:"บริการ", fFormula:"สูตร",
  sheetsCol:"จำนวนแผ่น", revenueTitle:"สรุปรายได้",
  revValue:"มูลค่างาน", revProject:"รายได้ที่โอนจ่าย (งบโครงการ)", revExternal:"รายได้ที่โอนจ่าย (รายได้ภายนอก / งานส่วนตัว)", revInternal:"งานบริการภายใน (ไม่เรียกเก็บ)",
  pdpaNotice:"ข้อมูลส่วนบุคคลของท่าน (ชื่อ-นามสกุล อีเมล และเบอร์โทรศัพท์) จะถูกเก็บรวบรวมและนำไปใช้เพื่อวัตถุประสงค์ในการติดต่อประสานงานและให้บริการของโรงพิมพ์เท่านั้น โดยเราจะปกป้องข้อมูลของท่านอย่างเคร่งครัดตาม พ.ร.บ.คุ้มครองข้อมูลส่วนบุคคล (PDPA)",
  pdpaConsentLabel:"รับทราบและยินยอมเงื่อนไขการใช้ข้อมูลส่วนบุคคล",
  reviewTitle:"สรุปคำขอก่อนส่ง", reviewSub:"ตรวจสอบข้อมูลก่อนส่งคำขอ เจ้าหน้าที่โรงพิมพ์จะตรวจสอบและดำเนินการต่อ",
  driveWarnShort:"โปรดยกเลิกการแชร์ลิงก์หลังงานเสร็จสิ้น เพื่อความปลอดภัยของไฟล์ท่าน",
  driveWarnFull:"เมื่อโรงพิมพ์ดำเนินการเสร็จสิ้นและท่านได้รับชิ้นงานเรียบร้อยแล้ว กรุณายกเลิกการแชร์ลิงก์นี้ เพื่อจำกัดสิทธิ์การเข้าถึงไฟล์งานของท่านจากบุคคลอื่น",
  submitOkMsg:"โรงพิมพ์ได้รับคำขอรับบริการจากท่านแล้ว ในระหว่างให้บริการ ท่านสามารถติดตามการให้บริการได้ที่",
  trackJobNo:"เลขที่งาน", trackService:"บริการ", trackStatus:"สถานะ", sendEmail:"ส่งอีเมล", sendEmailOk:"ส่งรายงานให้ทางอีเมลแล้ว",
  colLetter:"คอลัมน์", colName:"ชื่อคอลัมน์", colType:"ชนิด", colDesc:"คำอธิบาย",
  sheetRulesTitle:"กติกาการเก็บข้อมูลในชีต",
  setKicker:"ตั้งค่าระบบ", setTitle:"ผูก Google Drive กับ Google Sheet",
  setSub:"หน้านี้สำหรับแอดมิน กรอกรหัสสเปรดชีตและโฟลเดอร์ Drive ครั้งเดียว ระบบจะอ่านและเขียนข้อมูลทั้งหมดผ่านสองที่นี้",
  connState:"สถานะการเชื่อมต่อ", connOn:"เชื่อมต่อแล้ว", connOff:"ยังไม่เชื่อมต่อ",
  connWhenOn:"ตรวจล่าสุด 28 ส.ค. 2569 09:12", connWhenOff:"กดปุ่มทดสอบเพื่อตรวจสอบ",
  setOpen:"เปิดใน Google", setTest:"ทดสอบการเชื่อมต่อ",
  gSheetTitle:"Google Sheet (ฐานข้อมูลเดียว)", gDriveTitle:"Google Drive (ที่เก็บไฟล์)", gAccessTitle:"บัญชีและสิทธิ์",
  setStepsTitle:"ขั้นตอนการผูกครั้งแรก", setStepsSub:"ทำครั้งเดียวตอนติดตั้ง หลังจากนั้นระบบทำงานเองทั้งหมด",
  setFolderTitle:"โครงโฟลเดอร์ที่ระบบสร้างให้", setFolderSub:"ระบบสร้างโฟลเดอร์ย่อยตามปี เดือน และเลขที่งานอัตโนมัติ ไม่ต้องสร้างมือ",
  setRulesTitle:"ข้อกำหนดความปลอดภัย",
  setMapTitle:"เหตุการณ์ในระบบเขียนลงที่ไหน", setMapEvent:"เหตุการณ์", setMapSheet:"แท็บในชีต", setMapDrive:"การกระทำบน Drive",
  agentStripTitle:"ผู้ช่วยที่ทำงานอยู่เบื้องหลัง", agentStripSub:"งานซ้ำ ๆ ที่เคยทำด้วยมือ ถูกยกให้ผู้ช่วยอัตโนมัติดูแล คนเหลือหน้าที่ตัดสินใจ",
  agentBadge:"ผู้ช่วย AI", autoBadge:"อัตโนมัติ", agentHere:"ตรงนี้มีผู้ช่วยทำงานให้",
  footNote:"ต้นแบบหน้าจอ ข้อมูลตัวอย่าง ยังไม่เชื่อมต่อบริการจริง"
};

export const EN = {
  appName:"Printing Service Requests", org:"Printing House, Infrastructure Group", tel:"Tel. 02 579 1111 ext. 1114, 1552",
  roleReq:"Requester", roleAdmin:"Print shop admin", roleExec:"Executive",
  tabLanding:"Get service", tabWizard:"Service form", tabMine:"My requests", tabTrack:"Track job",
  tabQueue:"Job queue", tabMobile:"Mobile update", tabPrice:"Price master", tabRaw:"Raw data",
  tabSheet:"Sheet schema", tabSettings:"Connections", tabDash:"Dashboard", tabReport:"A4 report",
  kicker:"The printing house provides production and print & design services",
  landH1:"Sripatum University Printing House, at your service",
  landSub:"One form for every print job. Pick a service, answer only the questions that apply, see an estimate, and follow the job through to pickup.",
  ctaNew:"Start using the service", ctaTrack:"Track my jobs",
  pickService:"All services", pickServiceSub:"Prices come from the current price master. Items without a rule are marked awaiting quote — never shown as 0 baht.",
  chooseThis:"Choose this group",
  statReq:"Requests this month", statUser:"Unique requesters", statUnit:"Units served", statValue:"Value this month",
  oneForm:"Save your info once, use it for every service", newRequest:"Service request form", stepWord:"Step",
  ws1:"Pick services", ws2:"Details", ws3:"Attach files", ws4:"Review & submit",
  s1title:"Choose the services you need", s1sub:"One request can hold several items, e.g. colour print + binding.",
  s2title:"Requester information", dynFields:"Extra questions for the services you picked", qty:"Quantity",
  emptySel:"No service selected yet. Go back to step 1 to pick one.",
  s3title:"Attach your files", dropTitle:"Drop files here, or browse",
  dropHint:"Up to 10 files, 10 MB each · PDF, DOCX, XLSX, PPTX, JPG, PNG", chooseFile:"Choose files",
  driveTitle:"Files live in Google Drive", driveNote:"A folder is created per job number automatically. The sheet stores only the file id and link, never the file itself.",
  s4title:"Estimated price", s4sub:"This is an estimate. It becomes a confirmed price once the print shop reviews the job.",
  colService:"Service", colQty:"Qty", colUnitPrice:"Unit price", colAmount:"Amount",
  estTotal:"Estimated total", submit:"Submit request", cancel:"Cancel", back:"Back", next:"Next",
  submitOk:"Submitted. Job no.", submitOkSub:"A confirmation email went to your @spu.ac.th account and the row was appended to the JOBS tab.", viewTrack:"View job status",
  myJobs:"My requests", jobNo:"Job no.", sent:"Submitted", needBy:"Needed by", est:"Estimate", confirmed:"Confirmed", status:"Status",
  mineNote:"Tap a row for its timeline and files. Requesters only see their own jobs.",
  trackKicker:"Job tracking", timeline:"Status timeline", jobDetail:"Job details", filesTitle:"Files",
  filesNote:"Files open only for the requester and print shop staff. Never a public link.",
  queue:"Print shop queue", searchPh:"Search job no., name or unit", requester:"Requester", unit:"Unit", action:"Advance",
  kpiReceived:"Files received", kpiNew:"In production", kpiProd:"Production done", kpiReady:"Service done", kpiOver:"Overdue",
  mobileTitle:"Update status from a phone", mobileSub:"Built for staff at the machine: one tap changes the status, writes to the sheet and emails the requester.",
  mobileApp:"Today's jobs", today:"Today", fToday:"Today", fPending:"Open", fReady:"Ready",
  logTitle:"Status change log", logNote:"Every change is appended to STATUS_LOG with who, when and a note.",
  priceMaster:"Price master", priceMasterSub:"Admins edit prices here, no code changes. The rule used is snapshotted onto the job so past reports never shift.",
  addRule:"Add price rule", spec:"Condition", priceType:"Price type", price:"Price (THB)", effective:"Effective",
  priceRuleTitle:"Rules the system enforces",
  rawData:"Service request records", exportCsv:"Export CSV", exportXlsx:"Export XLSX",
  rawNote:"One row per line item. Totals are rolled up per job so nothing is double counted.",
  dashKicker:"Executive, read only", dashboard:"Service report",
  chartMonthly:"Jobs per month", chartTopService:"Most used services", chartStatus:"Jobs by status",
  fYear:"Year", fMonth:"Month", fUnitF:"Unit", allUnits:"All units",
  fYearBE:"Calendar year (B.E.)", fYearAcademic:"Academic year", fAllMonths:"Whole year", periodLabel:"Period",
  topRequesters:"Most frequent requesters (Top 10)", topUnitsValue:"Top units by value", timesSuffix:"requests",
  kpiAll:"Total requests", kpiUniqUser:"Unique users", kpiUniqUnit:"Units", kpiDone:"Completed", kpiValue:"Total value", kpiTat:"Avg turnaround",
  kpiAllSub:"Submitted and beyond, drafts excluded", kpiUserSub:"Distinct @spu.ac.th accounts", kpiUnitSub:"Units with requests",
  kpiDoneSub:"Completed in range", kpiValueSub:"Confirmed price first", kpiTatSub:"Submitted to completed",
  a4Title:"Monthly A4 report", a4Sub:"Totals derive from the same data as raw data and the dashboard.",
  printPdf:"Print / save PDF", a4Head:"Printing Service Summary", a4Period:"August 2025 (B.E. 2568)",
  a4Intro:"To the Director, Infrastructure Group — the printing house submits the monthly summary of service requests, grouped by unit and job type, as follows.",
  a4Foot:"Note: value uses the confirmed price. Items still awaiting confirmation show the estimate marked *. Cancelled jobs are excluded from value.",
  docNo:"Ref.", docDate:"Date", monthAug:"August", grandTotal:"Total",
  catProd:"Production", catDesign:"Print & design", catColor:"Colour print", cnt:"Jobs", amt:"Value",
  signName:"(Head of Printing House)", signRole:"Printing House, Infrastructure Group",
  sheetKicker:"Data architecture", sheetTitle:"Everything lives in one Google Sheet",
  sheetSub:"No separate database, no Supabase. One spreadsheet holds every tab; files sit in Google Drive and the sheet keeps only the file id and link.",
  tabsTitle:"Tabs in the spreadsheet", tabsSub:"Tap a tab to see its columns. Row 1 headers are the data contract: never reorder them, only append new columns at the end.",
  colLetter:"Col", colName:"Header", colType:"Type", colDesc:"Description",
  sheetRulesTitle:"How data must be written",
  setKicker:"System setup", setTitle:"Link Google Drive and Google Sheet",
  setSub:"Admin only. Enter the spreadsheet and Drive folder ids once; everything the system reads or writes goes through these two places.",
  connState:"Connection", connOn:"Connected", connOff:"Not connected",
  connWhenOn:"Last checked 28 Aug 2026, 09:12", connWhenOff:"Run a test to check",
  setOpen:"Open in Google", setTest:"Test connection",
  gSheetTitle:"Google Sheet (single database)", gDriveTitle:"Google Drive (file storage)", gAccessTitle:"Accounts & access",
  setStepsTitle:"First-time linking", setStepsSub:"Done once at install; after that the system runs on its own.",
  setFolderTitle:"Folder structure the system creates", setFolderSub:"Year, month and job-number folders are created automatically. Nothing is made by hand.",
  setRulesTitle:"Security requirements",
  setMapTitle:"Where each event is written", setMapEvent:"Event", setMapSheet:"Sheet tab", setMapDrive:"Drive action",
  agentStripTitle:"Assistants working in the background", agentStripSub:"The repetitive work moved to automated assistants. People are left with the decisions.",
  agentBadge:"AI assistant", autoBadge:"Automated", agentHere:"An assistant handles this step",
  footNote:"Screen prototype with sample data. Not yet connected to live services.",
  emailGateTitle:"Start a service request", emailGateLabel:"Email @spu.ac.th", emailGatePh:"e.g. somchai.j@spu.ac.th",
  emailGateBtn:"Continue", emailGateErr:"Please use an @spu.ac.th email address", emailGateFound:"Found your profile — check the fields below", emailGateNotFound:"No profile found. Please fill in every field.",
  wzService:"Services", wzDetails:"Details", wzFiles:"Files", wzReview:"Review",
  svcGroupProd:"Production", svcGroupDesign:"Print & design",
  prodColor:"Colour or B/W", prodColorColor:"Colour", prodColorBw:"B/W",
  prodSize:"Paper size", prodSizeA3:"A3 (large)", prodSizeA4:"A4 (regular)", prodSizeA5:"A5 (small)",
  prodPaperType:"Paper type", prodSides:"Sides", prodSidesOne:"Single sided", prodSidesTwo:"Double sided",
  prodOwnPaper:"I'll bring my own paper", prodOwnPaperWarn:"Production starts only after the print shop receives your paper.",
  prodQty:"Quantity (sheets)",
  prodQtyOriginal:"Original pages (sheets)", prodQtySets:"Number of sets",
  stapleLabel:"Stapling", stapleCorner:"Corner staple", stapleSide2:"Side staple, 2 points", stapleNone:"No staple",
  examTitle:"Exam paper details", examType:"Exam type", examMid:"Midterm", examOut:"Off-schedule exam",
  examSubject:"Course (code + title)", examSubjectPh:"e.g. BUS201 Principles of Marketing",
  examNote:"The faculty sends the exam file to the print shop. Fill in the duplicate-print details and name the course.",
  budgetTitle:"Budget", budgetSub:"Where the funding for this job comes from",
  budgetHas:"Budgeted (job value)", budgetProject:"Transfer (project budget)", budgetPersonal:"Transfer (personal budget)",
  budgetAttach:"Attach the approved budget", budgetAttachHint:"PDF or a photo of the approval document",
  budgetAcct:"SPU account number", budgetAcctPh:"SPU …",
  budgetSkip:"Exam papers and exercise sheets are a standard print shop service — no budget entry needed.",
  priceActive:"Active", priceOffLabel:"Disabled", priceToggleCol:"On/off",
  formulaTitle:"Calculation formulas", formulaSub:"Use these to check a total before confirming a price", calcTitle:"Calculator", calcOpenHint:"Open floating window", calcKbHint:"Keyboard works · Enter = equals · Esc closes", calcClear:"Clear",
  fCol:"Service", fFormula:"Formula",
  sheetsCol:"Sheets", revenueTitle:"Revenue breakdown",
  revValue:"Job value", revProject:"Transferred (project budget)", revExternal:"Transferred (external / personal)", revInternal:"Internal service (not charged)",
  pdpaNotice:"Your personal data (full name, email and phone number) is collected and used only to coordinate and deliver the print shop's services. It is protected under the Personal Data Protection Act (PDPA).",
  pdpaConsentLabel:"I acknowledge and consent to the personal data terms.",
  reviewTitle:"Review before you submit", reviewSub:"Check everything below. The print shop reviews and processes it next.",
  driveWarnShort:"Please stop sharing this link once the job is done", driveWarnFull:"Once the print shop has completed your job, please stop sharing this link to limit others' access to your files.",
  submitOkMsg:"The print shop has received your service request. You can track its progress at any time.",
  trackJobNo:"Job no.", trackService:"Service", trackStatus:"Status", sendEmail:"Send email", sendEmailOk:"The report has been emailed."
};

export const CATS = [
  { no:"01", th:"งานผลิต", en:"Production", items:[
    { id:"copy",  th:"ถ่ายเอกสาร", en:"Photocopying", unitTh:"แผ่น", unitEn:"sheets", price:0.5, spec:{th:"A4 ปอนด์ 70 แกรม ขาวดำ", en:"A4 bond 70 gsm, B/W"} },
    { id:"dup",   th:"พิมพ์สำเนา (ขาวดำ)", en:"Duplicate printing (B/W)", unitTh:"แผ่น", unitEn:"sheets", price:2, spec:{th:"A4 ปอนด์ 70 แกรม / ปอนด์สี 80 แกรม / การ์ดสี 180 แกรม", en:"A4 bond 70 gsm / coloured bond 80 gsm / 180 gsm card"} },
    { id:"exam",  th:"ข้อสอบ", en:"Exam papers", unitTh:"แผ่น", unitEn:"sheets", price:2, spec:{th:"สอบกลางภาค / สอบนอกตาราง · ใช้เงื่อนไขเดียวกับงานพิมพ์สำเนา", en:"Midterm / off-schedule; priced like duplicate printing"} },
    { id:"bind",  th:"เข้าเล่ม", en:"Binding", unitTh:"เล่ม", unitEn:"books", manual:true, spec:{th:"ยังไม่มีราคาในตารางปัจจุบัน", en:"No rule in the current price master"} }
  ]},
  { no:"02", th:"งานพิมพ์และออกแบบ", en:"Print & design", items:[
    { id:"card",  th:"นามบัตร", en:"Business cards", unitTh:"ใบ", unitEn:"cards", min:2.5, max:3, spec:{th:"ซิมโบแมทพลัส 250 แกรม · 1 ด้าน 2.50 / 2 ด้าน 3", en:"Simbo Matt Plus 250 gsm; 1-side 2.50, 2-side 3"} },
    { id:"cert",  th:"วุฒิบัตร", en:"Certificates", unitTh:"แผ่น", unitEn:"sheets", min:10, max:15, spec:{th:"โลโก้ SPU อักษรดำ 10 / หลายโลโก้อักษรสี 15", en:"SPU logo black text 10; multi-logo colour 15"} },
    { id:"layout",th:"จัดรูปเล่ม / ออกแบบ", en:"Layout & design", unitTh:"หน้า", unitEn:"pages", min:50, max:200, spec:{th:"ขาวดำ 50 / 4 สี 100–200 ต่อหน้า รวมออกแบบปก/งาน Artwork", en:"B/W 50; 4-colour 100–200 per page, incl. cover/artwork design"} }
  ]},
  { no:"03", th:"พริ้นสี", en:"Colour print", items:[
    { id:"a5", th:"พริ้นสี A5", en:"Colour print A5", unitTh:"แผ่น", unitEn:"sheets", manual:true, spec:{th:"ยังไม่มีราคา A5 ในเอกสารปัจจุบัน", en:"No A5 price in the current document"} },
    { id:"a4", th:"พริ้นสี A4", en:"Colour print A4", unitTh:"แผ่น", unitEn:"sheets", min:15, max:20, spec:{th:"ปอนด์ 70 แกรม 15 / ซิมโบแมทพลัส 250 แกรม 20", en:"Bond 70 gsm 15; Simbo Matt Plus 250 gsm 20"} },
    { id:"a3", th:"พริ้นสี A3", en:"Colour print A3", unitTh:"แผ่น", unitEn:"sheets", min:30, max:60, spec:{th:"ปอนด์ 80 แกรม 30–50 / ซิมโบแมทพลัส 60", en:"Bond 80 gsm 30–50; Simbo Matt Plus 60"} }
  ]}
];

export const DYN = {
  copy:[["ขนาดกระดาษ","Paper size","A4"],["ประเภทกระดาษ / แกรม","Paper / gsm","ปอนด์ 70 แกรม|Bond 70 gsm"],["ขาวดำ หรือ สี","Colour mode","ขาวดำ|Black & white"],["หน้าเดียว / สองหน้า","Sides","สองหน้า|Double sided"],["จำนวนต้นฉบับ (แผ่น)","Original pages","10"],["จำนวนชุดที่ต้องการ","Sets","5"],["นำกระดาษมาเอง","Own paper","ไม่|No"]],
  dup:[["ขนาดกระดาษ","Paper size","A4"],["ประเภทกระดาษ / แกรม","Paper / gsm","ปอนด์สี 80 แกรม|Coloured bond 80 gsm"],["จำนวนต้นฉบับ (แผ่น)","Original pages","12"],["จำนวนชุดที่ต้องการ","Sets","20"],["การเย็บชุด","Stapling","เย็บข้าง 2 จุด|Side staple, 2 points"]],
  exam:[["ประเภทการสอบ","Exam type","สอบกลางภาค|Midterm"],["รายวิชา (รหัสวิชา + ชื่อวิชา)","Course (code + title)","BUS201 หลักการตลาด|BUS201 Principles of Marketing"],["จำนวนต้นฉบับ (แผ่น)","Original pages","8"],["จำนวนชุดที่ต้องการ","Sets","120"],["การเย็บชุด","Stapling","เย็บมุม|Corner staple"]],
  bind:[["ประเภทการเข้าเล่ม","Binding type","ไสกาว|Perfect bound"],["จำนวนหน้าต่อเล่ม","Pages per book","180"]],
  card:[["หน้าเดียว / สองด้าน","Sides","สองด้าน|Double sided"],["แบบ","Template","แบบมหาวิทยาลัย|University template"],["ข้อความบนบัตร","Card text","ตามไฟล์แนบ|As attached"]],
  cert:[["รูปแบบโลโก้","Logo option","โลโก้ SPU + อักษรสีดำ|SPU logo + black text"],["เจียนขอบ 4 ด้าน","Trim 4 edges","ใช่ +3 บาท|Yes, +3 THB"]],
  layout:[["ประเภทงาน","Work type","จัดรูปเล่ม 4 สี|4-colour layout"],["ขนาดงาน","Size","A4"],["เข้าเล่มหรือไม่","Binding","ใช่|Yes"],["วันที่ต้องการ Proof","Proof date","02/09/2568"]],
  a5:[["ประเภทกระดาษ","Paper","ปอนด์ 80 แกรม|Bond 80 gsm"],["หน้าเดียว / สองหน้า","Sides","หน้าเดียว|Single sided"]],
  a4:[["ประเภทกระดาษ","Paper","ซิมโบแมทพลัส 250 แกรม|Simbo Matt Plus 250 gsm"],["หน้าเดียว / สองหน้า","Sides","หน้าเดียว|Single sided"],["นำกระดาษมาเอง","Own paper","ไม่|No"]],
  a3:[["ประเภทกระดาษ","Paper","ปอนด์ 80 แกรม|Bond 80 gsm"],["หน้าเดียว / สองหน้า","Sides","หน้าเดียว|Single sided"]]
};

export const ST = {
  RECEIVED:{th:"📥 ได้รับไฟล์แล้ว",en:"📥 Files received"},
  IN_PRODUCTION:{th:"🖨️ กำลังปริ้น / ถ่ายเอกสาร",en:"🖨️ Printing / photocopying"},
  PROD_DONE:{th:"🟢 งานเสร็จแล้ว มารับได้เลย!",en:"🟢 Job done — ready for pickup!"},
  SERVICE_DONE:{th:"🤝 รับกลับเรียบร้อย",en:"🤝 Picked up"}
};
export const FLOW = ["RECEIVED","IN_PRODUCTION","PROD_DONE","SERVICE_DONE"];

export const JOBS = [
  { no:"PRN-256808-0042", reqTh:"ผศ.ดร. อนงค์ ศรีวัฒน์", reqEn:"Asst. Prof. Anong Sriwat", unitTh:"คณะบริหารธุรกิจ", unitEn:"Business Administration", svc:"cert", sent:"05/08/2568", need:"12/08/2568", est:15000, conf:15000, qty:1000, status:"SERVICE_DONE", overdue:false },
  { no:"PRN-256808-0047", reqTh:"ปิยะดา ทองแท้", reqEn:"Piyada Thongtae", unitTh:"สำนักงานทะเบียน", unitEn:"Registrar Office", svc:"a4", sent:"11/08/2568", need:"15/08/2568", est:6000, conf:6000, qty:300, status:"PROD_DONE", overdue:false },
  { no:"PRN-256808-0051", reqTh:"กิตติ วรรณศิลป์", reqEn:"Kitti Wannasilp", unitTh:"คณะนิเทศศาสตร์", unitEn:"Communication Arts", svc:"layout", sent:"14/08/2568", need:"20/08/2568", est:3000, conf:0, qty:1, status:"PROD_DONE", overdue:false },
  { no:"PRN-256808-0055", reqTh:"สมชาย ใจดี", reqEn:"Somchai Jaidee", unitTh:"กลุ่มงานกิจการนักศึกษา", unitEn:"Student Affairs", svc:"copy", sent:"18/08/2568", need:"19/08/2568", est:2500, conf:2500, qty:5000, status:"IN_PRODUCTION", overdue:true },
  { no:"PRN-256808-0058", reqTh:"วราภรณ์ สุขใจ", reqEn:"Waraporn Sukjai", unitTh:"กลุ่มงานการคลัง", unitEn:"Finance Group", svc:"card", sent:"20/08/2568", need:"27/08/2568", est:900, conf:0, qty:300, status:"IN_PRODUCTION", overdue:false },
  { no:"PRN-256808-0061", reqTh:"ดร. ณัฐพงษ์ เรืองชัย", reqEn:"Dr. Nattapong Ruangchai", unitTh:"คณะวิศวกรรมศาสตร์", unitEn:"Engineering", svc:"a5", sent:"24/08/2568", need:"29/08/2568", est:0, conf:0, qty:200, status:"IN_PRODUCTION", overdue:false },
  { no:"PRN-256808-0064", reqTh:"สุภาพร มั่นคง", reqEn:"Supaporn Mankong", unitTh:"กลุ่มอำนวยการกลาง", unitEn:"Central Administration", svc:"layout", sent:"26/08/2568", need:"05/09/2568", est:9000, conf:0, qty:60, status:"IN_PRODUCTION", overdue:false },
  { no:"PRN-256808-0066", reqTh:"ธนกร พัฒนา", reqEn:"Thanakorn Pattana", unitTh:"กลุ่มงานกิจการสัมพันธ์", unitEn:"External Relations", svc:"bind", sent:"27/08/2568", need:"03/09/2568", est:0, conf:0, qty:40, status:"RECEIVED", overdue:false }
];

export const SHEET_TABS = [
  { name:"JOBS", cols:[
    ["A","job_no","TEXT","เลขที่งาน PRN-YYYYMM-0001 ห้ามซ้ำ","Job number PRN-YYYYMM-0001, unique"],
    ["B","submitted_at","DATETIME","เวลาส่งคำขอ เขตเวลา Asia/Bangkok","Submission time, Asia/Bangkok"],
    ["C","requester_email","TEXT","อีเมล @spu.ac.th จากการล็อกอิน","@spu.ac.th account from sign-in"],
    ["D","requester_name","TEXT","ชื่อ-สกุลผู้ขอ","Requester full name"],
    ["E","position_type","TEXT","ผู้บริหาร / อาจารย์ / เจ้าหน้าที่ / อื่น ๆ","Executive / lecturer / staff / other"],
    ["F","phone","TEXT","เบอร์ติดต่อ","Contact number"],
    ["G","unit_code","TEXT","รหัสหน่วยงาน อ้างแท็บ UNITS","Unit code, references UNITS"],
    ["H","required_date","DATE","วันที่ต้องการรับงาน","Date the job is needed"],
    ["I","purpose","TEXT","วัตถุประสงค์และรายละเอียด","Purpose and details"],
    ["J","status","TEXT","สถานะล่าสุด ค่าจาก STATUS_MASTER","Current status from STATUS_MASTER"],
    ["K","estimated_amount","NUMBER","ราคาประมาณการรวม เว้นว่างถ้าประเมินไม่ได้","Estimated total; blank if not quotable"],
    ["L","confirmed_amount","NUMBER","ราคายืนยันโดยแอดมิน","Admin-confirmed total"],
    ["M","completed_at","DATETIME","เวลางานเสร็จ ใช้คำนวณ turnaround","Completion time, drives turnaround"],
    ["N","drive_folder_id","TEXT","รหัสโฟลเดอร์ Drive ของงานนี้","Drive folder id for this job"]
  ]},
  { name:"JOB_ITEMS", cols:[
    ["A","item_id","TEXT","รหัสรายการ job_no + ลำดับ","Line id: job_no + index"],
    ["B","job_no","TEXT","อ้างแท็บ JOBS","References JOBS"],
    ["C","service_code","TEXT","รหัสบริการ อ้าง SERVICES","Service code, references SERVICES"],
    ["D","variant_snapshot","TEXT","ขนาด กระดาษ แกรม สี หน้า เก็บเป็นข้อความ","Size, paper, gsm, colour, sides as text"],
    ["E","quantity","NUMBER","จำนวนตามหน่วยของบริการ","Quantity in the service unit"],
    ["F","unit","TEXT","แผ่น / หน้า / ชุด / งาน","sheet / page / set / job"],
    ["G","unit_price","NUMBER","ราคาต่อหน่วยที่ใช้คำนวณ","Unit price used"],
    ["H","estimated_amount","NUMBER","จำนวน × ราคาต่อหน่วย","quantity × unit price"],
    ["I","confirmed_amount","NUMBER","ยอดยืนยันรายรายการ","Confirmed amount per line"],
    ["J","price_rule_id","TEXT","รหัสกฎราคาที่ใช้","Price rule id applied"],
    ["K","price_rule_snapshot","TEXT","สำเนากฎราคาตอนคำนวณ ทำให้รายงานย้อนหลังไม่เปลี่ยน","Rule snapshot so old reports stay fixed"],
    ["L","override_reason","TEXT","เหตุผลเมื่อแอดมินแก้ราคา","Reason when an admin overrides"]
  ]},
  { name:"PRICE_RULES", cols:[
    ["A","rule_id","TEXT","รหัสกฎราคา","Rule id"],
    ["B","service_code","TEXT","บริการที่กฎนี้ใช้","Service the rule applies to"],
    ["C","condition","TEXT","ขนาด กระดาษ แกรม สี หน้า","Size, paper, gsm, colour, sides"],
    ["D","price_type","TEXT","PER_SHEET / PER_PAGE / PER_ITEM / PER_SET / FIXED_PRICE / PRICE_RANGE / MANUAL_QUOTE / ADD_ON","Same enum"],
    ["E","price","NUMBER","ราคาเดียว เว้นว่างถ้าเป็นช่วง","Single price; blank for a range"],
    ["F","min_price","NUMBER","ต่ำสุดของช่วง","Range minimum"],
    ["G","max_price","NUMBER","สูงสุดของช่วง","Range maximum"],
    ["H","effective_from","DATE","วันเริ่มใช้","Effective from"],
    ["I","effective_to","DATE","วันสิ้นสุด เว้นว่างถ้ายังใช้อยู่","Effective to; blank if current"],
    ["J","active","BOOLEAN","เปิด/ปิดใช้งาน","Active flag"],
    ["K","note","TEXT","หมายเหตุ เช่น ค่าเจียนขอบเฉพาะวุฒิบัตร","Notes, e.g. trim add-on for certificates only"]
  ]},
  { name:"UNITS", cols:[
    ["A","unit_code","TEXT","รหัสหน่วยงาน","Unit code"],
    ["B","unit_name","TEXT","ชื่อหน่วยงาน","Unit name"],
    ["C","parent_group","TEXT","กลุ่มหลัก ใช้เป็นหัวกลุ่มในรายงาน A4","Parent group; the A4 group header"],
    ["D","display_order","NUMBER","ลำดับการแสดงในรายงาน","Order in the report"],
    ["E","active","BOOLEAN","ยังใช้งานอยู่หรือไม่","Active flag"]
  ]},
  { name:"USERS", cols:[
    ["A","email","TEXT","อีเมล @spu.ac.th เป็นคีย์","@spu.ac.th email, primary key"],
    ["B","full_name","TEXT","ชื่อ-สกุล","Full name"],
    ["C","role","TEXT","REQUESTER / ADMIN / EXECUTIVE ผู้ใช้ใหม่เป็น REQUESTER","REQUESTER / ADMIN / EXECUTIVE; new users start as REQUESTER"],
    ["D","unit_code","TEXT","หน่วยงานสำหรับเติมฟอร์มอัตโนมัติ","Unit used to prefill the form"],
    ["E","phone","TEXT","เบอร์ติดต่อ","Contact number"],
    ["F","active","BOOLEAN","ปิดการเข้าใช้ได้โดยไม่ลบแถว","Disable access without deleting the row"]
  ]},
  { name:"FILES", cols:[
    ["A","file_id","TEXT","รหัสไฟล์บน Google Drive","Google Drive file id"],
    ["B","job_no","TEXT","งานที่ไฟล์นี้สังกัด","Job the file belongs to"],
    ["C","file_name","TEXT","ชื่อไฟล์เดิมของผู้ส่ง","Original file name"],
    ["D","mime_type","TEXT","ชนิดไฟล์ที่ตรวจแล้วฝั่งเซิร์ฟเวอร์","Server-validated MIME type"],
    ["E","file_size","NUMBER","ขนาดไบต์","Size in bytes"],
    ["F","file_category","TEXT","requester / admin / proof / final","requester / admin / proof / final"],
    ["G","uploaded_by","TEXT","อีเมลผู้อัปโหลด","Uploader email"],
    ["H","uploaded_at","DATETIME","เวลาอัปโหลด","Upload time"],
    ["I","web_view_link","TEXT","ลิงก์เปิดไฟล์แบบจำกัดสิทธิ์ ไม่ใช่ลิงก์สาธารณะ","Permissioned view link, never public"]
  ]},
  { name:"STATUS_LOG", cols:[
    ["A","log_id","TEXT","รหัสบันทึก","Log id"],
    ["B","job_no","TEXT","งานที่เปลี่ยนสถานะ","Job changed"],
    ["C","old_status","TEXT","สถานะก่อนเปลี่ยน","Previous status"],
    ["D","new_status","TEXT","สถานะใหม่","New status"],
    ["E","changed_by","TEXT","อีเมลผู้เปลี่ยน","Who changed it"],
    ["F","changed_at","DATETIME","เวลาที่เปลี่ยน","When"],
    ["G","note","TEXT","หมายเหตุสั้น ๆ จากเจ้าหน้าที่","Short staff note"],
    ["H","channel","TEXT","web / mobile ใช้ดูว่าอัปเดตจากไหน","web / mobile origin"]
  ]},
  { name:"NOTIFY_LOG", cols:[
    ["A","notify_id","TEXT","รหัสการแจ้ง","Notification id"],
    ["B","job_no","TEXT","งานที่แจ้ง","Job notified"],
    ["C","template_code","TEXT","แม่แบบอีเมลที่ใช้","Email template used"],
    ["D","recipient","TEXT","ผู้รับ","Recipient"],
    ["E","status","TEXT","sent / failed / retry","sent / failed / retry"],
    ["F","sent_at","DATETIME","เวลาส่ง","Sent at"],
    ["G","error","TEXT","ข้อความผิดพลาด ถ้ามี","Error text if any"]
  ]},
  { name:"SETTINGS", cols:[
    ["A","key","TEXT","ชื่อค่าตั้งค่า เช่น drive_root_id","Setting key, e.g. drive_root_id"],
    ["B","value","TEXT","ค่าที่ใช้ ห้ามเก็บรหัสลับในชีต","Value; never store secrets here"],
    ["C","updated_by","TEXT","แอดมินที่แก้ล่าสุด","Admin who last edited"],
    ["D","updated_at","DATETIME","เวลาที่แก้","When"],
    ["E","note","TEXT","คำอธิบายค่านี้","What this setting does"]
  ]}
];

export const PRICE_RULES = [
  ["copy","A4 ปอนด์ 70 แกรม ขาวดำ|A4 bond 70 gsm B/W","PER_SHEET","0.50","01/10/2567","active"],
  ["copy","A4 ปอนด์สี 80 แกรม|A4 coloured bond 80 gsm","PER_SHEET","2.00","01/10/2567","active"],
  ["copy","A3 ปอนด์ 80 แกรม|A3 bond 80 gsm","PER_SHEET","5.00","01/10/2567","active"],
  ["dup","A4 ปอนด์ 70 แกรม|A4 bond 70 gsm","PER_SHEET","2.00","01/10/2567","active"],
  ["dup","การ์ดสี 180 แกรม ปกชุด|Coloured card 180 gsm, cover","PER_SHEET","5.00","01/10/2567","active"],
  ["exam","ข้อสอบ A4 ปอนด์ 70 แกรม|Exam paper, A4 bond 70 gsm","PER_SHEET","2.00","01/10/2567","active"],
  ["card","1 ด้าน ซิมโบแมทพลัส 250 แกรม|1-side Simbo Matt Plus 250 gsm","PER_ITEM","2.50","01/10/2567","active"],
  ["card","2 ด้าน แบบมหาวิทยาลัย|2-side university template","PER_ITEM","3.00","01/10/2567","active"],
  ["cert","โลโก้ SPU + อักษรสีดำ|SPU logo + black text","PER_SHEET","10.00","01/10/2567","active"],
  ["cert","โลโก้ SPU + โลโก้อื่น + อักษรสี|SPU + other logos, colour text","PER_SHEET","15.00","01/10/2567","active"],
  ["cert","เจียนขอบ 4 ด้าน เฉพาะวุฒิบัตร|Trim 4 edges, certificates only","ADD_ON","+3.00","01/10/2567","active"],
  ["a4","A4 ปอนด์ 70 แกรม|A4 bond 70 gsm","PER_SHEET","15.00","01/10/2567","active"],
  ["a4","A4 ซิมโบแมทพลัส 250 แกรม|A4 Simbo Matt Plus 250 gsm","PER_SHEET","20.00","01/10/2567","active"],
  ["a4","MOU สครีม 180 แกรม หน้าโลโก้ 4 สี|MOU, Scream 180 gsm, 4-colour logo page","PER_PAGE","20.00","01/10/2567","active"],
  ["a4","MOU สครีม 180 แกรม หน้าอักษรสีดำ|MOU, Scream 180 gsm, black text page","PER_PAGE","10.00","01/10/2567","active"],
  ["a4","F4 นำกระดาษมาเอง|F4, own paper","PER_SHEET","20.00","01/10/2567","active"],
  ["a3","A3 ปอนด์ 80 แกรม|A3 bond 80 gsm","PRICE_RANGE","30–50","01/10/2567","active"],
  ["a3","A3 ซิมโบแมทพลัส 250 แกรม|A3 Simbo Matt Plus 250 gsm","PER_SHEET","60.00","01/10/2567","active"],
  ["layout","จัดรูปเล่มขาวดำ|B/W layout","PER_PAGE","50.00","01/10/2567","active"],
  ["layout","จัดรูปเล่ม 4 สี|4-colour layout","PRICE_RANGE","100–200","01/10/2567","active"],
  ["a5","พริ้นสี A5|Colour print A5","MANUAL_QUOTE","รอกำหนด|To be set","—","pending"],
  ["bind","เข้าเล่มทั่วไป|General binding","MANUAL_QUOTE","รอกำหนด|To be set","—","pending"]
];

export const FORMULAS = [
  ["copy","จำนวนต้นฉบับ × จำนวนชุด × ราคาต่อแผ่น|Originals × sets × price per sheet"],
  ["dup","จำนวนต้นฉบับ × จำนวนชุด × ราคาต่อแผ่น (+ ปกชุด ถ้ามี)|Originals × sets × sheet price (+ cover)"],
  ["exam","จำนวนต้นฉบับ × จำนวนชุด × ราคาต่อแผ่น|Originals × sets × price per sheet"],
  ["cert","จำนวนแผ่น × ราคาตามรูปแบบโลโก้ (+3 ต่อแผ่น ถ้าเจียนขอบ)|Sheets × logo-option price (+3 per sheet if trimmed)"],
  ["card","จำนวนใบ × ราคาต่อใบตามจำนวนด้าน|Cards × price per card by sides"],
  ["layout","จำนวนหน้า × ราคาต่อหน้า (ช่วง 4 สี รอแอดมินยืนยัน)|Pages × page rate (4-colour range needs admin confirmation)"],
  ["a4","จำนวนแผ่น × ราคาตามชนิดกระดาษ|Sheets × price by paper type"],
  ["a3","จำนวนแผ่น × ราคาตามชนิดกระดาษ|Sheets × price by paper type"],
  ["bind","คิดรายเล่ม รอแอดมินกำหนดราคา|Quoted per book by the admin"]
];

export const AGENTS = [
  { key:"price", face:"calc",
    th:"ผู้ช่วยประเมินราคา", en:"Quoting assistant",
    thWhat:"อ่านรายการที่เลือก จับคู่กฎใน PRICE_RULES แล้วสรุปราคาให้ทันทีในหน้าฟอร์ม ราคาช่วงหรือรายการที่ไม่มีกฎ ส่งต่อให้คนยืนยัน ไม่เดาเลข",
    enWhat:"Reads the picked items, matches PRICE_RULES and totals the estimate in the form. Ranges and unpriced items are handed to a human — it never guesses.",
    thTag:"ผู้ช่วย AI", enTag:"AI assistant", thSaved:"ลดเวลาคิดราคาต่องาน", enSaved:"Quoting time per job", metric:"~6 นาที|~6 min" },
  { key:"file", face:"folder",
    th:"ผู้ช่วยจัดไฟล์", en:"Filing assistant",
    thWhat:"สร้างโฟลเดอร์ตามปี เดือน และเลขที่งานบน Drive ตั้งชื่อไฟล์ให้เป็นระบบ แล้วเขียนรหัสไฟล์กลับลงชีตให้เอง",
    enWhat:"Creates the year / month / job folders on Drive, renames files to a consistent pattern and writes the file ids back to the sheet.",
    thTag:"อัตโนมัติ", enTag:"Automated", thSaved:"ไฟล์ที่จัดเข้าที่เอง", enSaved:"Files filed automatically", metric:"100%" },
  { key:"notify", face:"mail",
    th:"ผู้ช่วยแจ้งสถานะ", en:"Notifying assistant",
    thWhat:"ทุกครั้งที่สถานะเปลี่ยน ร่างอีเมลจากแม่แบบ ใส่เลขที่งานและลิงก์ติดตาม ส่งให้ผู้ขอ แล้วบันทึกผลลง NOTIFY_LOG",
    enWhat:"On every status change it fills the email template with the job number and tracking link, sends it, and logs the result in NOTIFY_LOG.",
    thTag:"อัตโนมัติ", enTag:"Automated", thSaved:"โทรตามสถานะที่หายไป", enSaved:"Status phone calls avoided", metric:"−80%" },
  { key:"report", face:"chart",
    th:"ผู้ช่วยสรุปรายงาน", en:"Reporting assistant",
    thWhat:"รวมยอดรายหน่วยงานและประเภทงานจากชีตชุดเดียว ร่างรายงาน A4 ตามแบบเดิม พร้อมสรุปสั้นให้ผู้บริหารอ่านก่อนเซ็น",
    enWhat:"Rolls up units and job types from the one sheet, drafts the A4 report in the familiar layout, and writes a short read-first summary for the executive.",
    thTag:"ผู้ช่วย AI", enTag:"AI assistant", thSaved:"เวลาทำรายงานรายเดือน", enSaved:"Monthly report effort", metric:"2 วัน → 5 นาที|2 days → 5 min" }
];

AGENTS.push({ key:"triage", face:"queue",
  th:"ผู้ช่วยจัดคิว", en:"Triage assistant",
  thWhat:"เรียงคิวตามวันที่ต้องการรับงาน ชูงานที่เสี่ยงเกินกำหนดขึ้นบน และเตือนเจ้าหน้าที่เมื่อมีงานค้างรอข้อมูลเพิ่ม",
  enWhat:"Orders the queue by due date, floats at-risk jobs to the top and nudges staff when a job is stuck waiting for information.",
  thTag:"ผู้ช่วย AI", enTag:"AI assistant", thSaved:"งานเกินกำหนดที่ลดลง", enSaved:"Fewer overdue jobs", metric:"−45%" });

export const SAMPLE_USERS = {
  "somchai.j@spu.ac.th": { titleTh:"นาย", titleEn:"Mr.", nameTh:"สมชาย ใจดี", nameEn:"Somchai Jaidee",
    posTh:"เจ้าหน้าที่", posEn:"Staff", unitTh:"กลุ่มงานกิจการนักศึกษา", unitEn:"Student Affairs", phone:"081 234 5678" },
  "anong.s@spu.ac.th": { titleTh:"ผศ.ดร.", titleEn:"Asst. Prof. Dr.", nameTh:"อนงค์ ศรีวัฒน์", nameEn:"Anong Sriwat",
    posTh:"อาจารย์", posEn:"Lecturer", unitTh:"คณะบริหารธุรกิจ", unitEn:"Business Administration", phone:"081 555 2211" },
  "piyada.t@spu.ac.th": { titleTh:"นางสาว", titleEn:"Ms.", nameTh:"ปิยะดา ทองแท้", nameEn:"Piyada Thongtae",
    posTh:"เจ้าหน้าที่", posEn:"Staff", unitTh:"สำนักงานทะเบียน", unitEn:"Registrar Office", phone:"082 331 9087" }
};

export const PAGE_AGENT = {
  wizard:{ key:"price", th:"ผู้ช่วยประเมินราคากำลังคิดยอดให้ระหว่างคุณกรอก", en:"The quoting assistant totals the estimate as you type." },
  queue:{ key:"triage", th:"ผู้ช่วยจัดคิวเรียงงานตามวันที่ต้องการรับ และชูงานที่เสี่ยงเกินกำหนดขึ้นบน", en:"The triage assistant orders the queue by due date and floats at-risk jobs to the top." },
  mobile:{ key:"notify", th:"กดปุ่มเดียว ผู้ช่วยเขียนลงชีต ส่งอีเมล และบันทึกล็อกให้ครบ", en:"One tap and the assistant writes the sheet, sends the email and logs it." },
  report:{ key:"report", th:"รายงานฉบับนี้ผู้ช่วยร่างจากข้อมูลจริง คนแค่ตรวจและเซ็น", en:"The assistant drafts this from live data; a person reviews and signs." },
  dash:{ key:"report", th:"ผู้ด้านการบริหารข้อมูลด้านงบประมาณ", en:"Every figure recomputes from the one sheet — nothing is tallied by hand." },
  settings:{ key:"file", th:"ผูกครั้งเดียว ผู้ช่วยจัดไฟล์ดูแลโฟลเดอร์และสิทธิ์ต่อเอง", en:"Link once; the filing assistant maintains folders and permissions after that." },
  sheet:{ key:"file", th:"ผู้ช่วยเขียนข้อมูลตามลำดับคอลัมน์นี้เท่านั้น ไม่แก้หัวตาราง", en:"Assistants only ever append along these columns; headers are never touched." }
};
